apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgv-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lgv
  template:
    metadata:
      labels:
        app: lgv
    spec:
      containers:
      - name: lgv
        image: mbeng44/lgv-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lgv-service
spec:
  selector:
    app: lgv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

