
apiVersion: v1
kind: Service
metadata:
  name: load-generator-votes
spec:
  selector:
    app: mbrng44/load-generator-votes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

